package edu.gmu.cs.infs614.webdealer.model;

import java.sql.Connection;
import java.sql.SQLException;

import javafx.beans.property.SimpleIntegerProperty;
import javafx.beans.property.SimpleStringProperty;

/* Customer model
CREATE TABLE Customer( 
customer_ID INTEGER, 
first_name VARCHAR2(30), 
last_name VARCHAR2(30), 
age INTEGER, 
email_address VARCHAR2(100), 
gender VARCHAR2(1), 
PRIMARY KEY (customer_ID)
);
INSERT INTO Customer VALUES (seq_customer.nextval,'John','Doe','30','jdoe@gmu.edu','m');
*/

// Immutable tuple
public class Customer {

	private final SimpleIntegerProperty cID; 
	private final SimpleStringProperty cFirstName;
	private final SimpleStringProperty cLastName;
	private final SimpleIntegerProperty cAge;
	private final SimpleStringProperty cEmailAddress;
	private final SimpleStringProperty cGender;
	private String user;
	private String pass;
	// DB connector
	private Connection conn = new CustomerConnection("wward5","password").getConnection();
	
	// Think about how we can model the key that's generated by Oracle
	public Customer(String cFirstName, String cLastName, Integer cAge, String cEmailAddress, String cGender) {
		this.cID = new SimpleIntegerProperty(create(cFirstName,cLastName,cAge,cEmailAddress,cGender));
		this.cFirstName = new SimpleStringProperty(cFirstName);
		this.cLastName = new SimpleStringProperty(cFirstName);
		this.cAge = new SimpleIntegerProperty(cAge);
		this.cEmailAddress = new SimpleStringProperty(cEmailAddress);
		this.cGender = new SimpleStringProperty(cGender);
		System.out.println("Customer constructed");
	}

	// CRUD
	private int create(
			String cFirstName, String cLastName, 
			Integer cAge, String cEmailAddress, String cGender) {
		
		String sql = "BEGIN INSERT INTO " +
						"Customer (customer_ID,first_name,last_name,age,email_address,gender) " +
						"VALUES (seq_customer.nextval, ?, ?, ?, ?, ?) RETURNING customer_ID INTO ?; END;";
		
		java.sql.CallableStatement stmt = null;
		
		
		int generatedKey = 0;
		
		try {
			stmt = conn.prepareCall(sql);
			stmt.setString(1, cFirstName);
			stmt.setString(2, cLastName);
			stmt.setInt(3, cAge); 
			stmt.setString(4, cEmailAddress);
			stmt.setString(5, cGender);
			
			stmt.registerOutParameter(6, java.sql.Types.INTEGER);	
			stmt.execute();
			generatedKey = stmt.getInt(6);
			stmt.close();
			
		} catch (SQLException sqle) {
			System.err.println("Customer insert error: "+sqle);
		}
		System.out.println("Customer_ID: "+generatedKey);
		return generatedKey;
	}
	
	
	// getters 
	
	public Integer getCID() {
		return cID.get();
	}
	
	public String getCFirstName() {
		return cFirstName.get();
	}

	public String getCLastName() {
		return cLastName.get();
	}

	public Integer getCAge() {
		return cAge.get();
	}

	public String getCEmailAddress() {
		return cEmailAddress.get();
	}

	public String getCGender() {
		return cGender.get();
	}

	
	
	
}
