package edu.gmu.cs.infs614.webdealer.model;

import java.sql.Connection;

import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.ArrayList;
//import java.util.Calendar;
import java.sql.Date;
import java.text.DateFormat;
import java.text.SimpleDateFormat;




import javafx.beans.property.SimpleDoubleProperty;
import javafx.beans.property.SimpleIntegerProperty;
import javafx.beans.property.SimpleStringProperty;
import javafx.scene.control.TextField;
import edu.gmu.cs.infs614.webdealer.AppUtil;
import edu.gmu.cs.infs614.webdealer.model.connector.DealConnection;


import edu.gmu.cs.infs614.webdealer.view.FormValidation;





//Immutable tuple (aka primary key)

/*deal_ID INTEGER,
expiration_date DATE,
description VARCHAR2(500),
quantity_limit INTEGER,
original_price REAL,
deal_price REAL,
sale_start_time DATE,
sale_end_time DATE,
location_ID INTEGER,
category_ID INTEGER,
merchant_ID INTEGER
*/

public class Deal {
	
	java.sql.Date sqlDate;
	DateFormat dateFormat = new SimpleDateFormat("dd-MMM-YYYY");
	
	public boolean isInDatabase = false;
	private SimpleIntegerProperty dID; 
	private SimpleStringProperty dExpDate;
	private SimpleStringProperty dDescription;
	private SimpleIntegerProperty dQuantity;
	private SimpleDoubleProperty dOrigPrice;
	private SimpleDoubleProperty dDealPrice;
	private SimpleStringProperty dSaleStart;
	private SimpleStringProperty dSaleEnd;
	private SimpleIntegerProperty lID;
	private SimpleIntegerProperty catID;
	private SimpleIntegerProperty mID;
	private static Connection conn;

	public Deal(Connection conn, Integer deal_ID, String expiration_date, String description, Integer quantity_limit,Double original_price, 
			Double deal_price, String sale_start_time, String sale_end_time, Integer location_ID, Integer category_ID, Integer merchant_ID){
		this.dID=null;
		this.dExpDate=null;
		this.dDescription=null;
		this.dQuantity=null;
		this.dOrigPrice=null;
		this.dDealPrice=null;
		this.dSaleStart=null;
		this.dSaleEnd=null;
		this.lID=null;
		this.catID=null;
		this.mID=null;
		Deal.conn=conn;
		// create a new deal in the database
		if(deal_ID == null) {
			int result = create(expiration_date,description,quantity_limit,original_price,deal_price,sale_start_time,sale_end_time,location_ID,category_ID,merchant_ID);
			if(result == -1) {
				isInDatabase = false;
				return;
			}
			else {
				isInDatabase = true;
			}
			
			this.dID = new SimpleIntegerProperty(result);
					
			}
		// create just a deal view
				else {
					this.dID = new SimpleIntegerProperty(deal_ID);
				}
				
				
				this.dExpDate=new SimpleStringProperty(expiration_date);
				this.dDescription=new SimpleStringProperty(description);
				this.dQuantity=new SimpleIntegerProperty(quantity_limit);
				this.dOrigPrice=new SimpleDoubleProperty(original_price);
				this.dDealPrice=new SimpleDoubleProperty(deal_price);
				this.dSaleStart=new SimpleStringProperty(sale_start_time);
				this.dSaleEnd=new SimpleStringProperty(sale_end_time);
				this.lID=new SimpleIntegerProperty(location_ID);
				this.catID=new SimpleIntegerProperty(category_ID);
				this.mID=new SimpleIntegerProperty(merchant_ID);
				AppUtil.console("Deal constructed");
				
				
				
			}
	// Think about how we can model the key that's generated by Oracle	
		public Deal(
				Connection conn,
				TextField tfDeal_ID,
				TextField tfexpiration_date,
				TextField tfdescription,
				TextField tfquantity_limit,
				TextField tforiginal_price,
				TextField tfdeal_price,
				TextField tfsale_start_time,
				TextField tfsale_end_time,
				TextField tflocation_ID,
				TextField tfcategory_ID,
				TextField tfmerchant_ID) {
			Deal.conn = conn;
			// had to check for null before calling tfDealID.getText(), so we just copied the constructor code
			this.dID=null;
			this.dExpDate=null;
			this.dDescription=null;
			this.dQuantity=null;
			this.dOrigPrice=null;
			this.dDealPrice=null;
			this.dSaleStart=null;
			this.dSaleEnd=null;
			this.lID=null;
			this.catID=null;
			this.mID=null;
			
			
			if(tfDeal_ID == null) {
				int result = create(tfexpiration_date.getText(),tfdescription.getText(),Integer.parseInt(tfquantity_limit.getText()),Double.parseDouble(tforiginal_price.getText()),Double.parseDouble(tfdeal_price.getText()),
						tfsale_start_time.getText(),tfsale_end_time.getText(),Integer.parseInt(tflocation_ID.getText()),Integer.parseInt(tfcategory_ID.getText()),Integer.parseInt(tfmerchant_ID.getText()));
				if(result == -1) {
					isInDatabase = false;
					return;
				}
				else {
					isInDatabase = true;
				}
				this.dID = new SimpleIntegerProperty(result);
				}
			else {
				this.dID = new SimpleIntegerProperty(Integer.parseInt(tfDeal_ID.getText()));
			}
			
			
			this.dExpDate=new SimpleStringProperty(tfexpiration_date.getText());
			this.dDescription=new SimpleStringProperty(tfdescription.getText());
			this.dQuantity=new SimpleIntegerProperty(Integer.parseInt(tfquantity_limit.getText()));
			this.dOrigPrice=new SimpleDoubleProperty(Double.parseDouble(tforiginal_price.getText()));
			this.dDealPrice=new SimpleDoubleProperty(Double.parseDouble(tfdeal_price.getText()));
			this.dSaleStart=new SimpleStringProperty(tfsale_start_time.getText());
			this.dSaleEnd=new SimpleStringProperty(tfsale_end_time.getText());
			this.lID=new SimpleIntegerProperty(Integer.parseInt(tflocation_ID.getText()));
			this.catID=new SimpleIntegerProperty(Integer.parseInt(tfcategory_ID.getText()));
			this.mID=new SimpleIntegerProperty(Integer.parseInt(tfmerchant_ID.getText()));

			AppUtil.console("Deal constructed");
		}	

		// CRUD
		private int create(String expiration_date, String description, Integer quantity_limit,Double original_price, 
				Double deal_price, String sale_start_time, String sale_end_time, Integer location_ID, Integer category_ID, Integer merchant_ID) {
			
			if(!connect()) AppUtil.console("Not able to connect to database!");
			
			String sql = "BEGIN INSERT INTO " +
							"Deal (deal_ID,expiration_date,description,quantity_limit,original_price,deal_price,sale_start_name," +
							"sale_end_time,location_ID,category_ID,merchant_ID) " +
							"VALUES (seq_customer.nextval, ?,?,?,?,?,?,?,?,?,?,?) RETURNING deal_ID INTO ?; END;";
			
			java.sql.CallableStatement stmt = null;
			
			
			int generatedKey = 0;
			
			try {
				stmt = conn.prepareCall(sql);
				stmt.setString(1, expiration_date);
				stmt.setString(2, description);
				stmt.setInt(3, quantity_limit);
				stmt.setDouble(4, original_price);
				stmt.setDouble(5, deal_price);
				stmt.setString(6, sale_start_time);
				stmt.setString(7, sale_end_time);
				stmt.setInt(8, location_ID);
				stmt.setInt(9, category_ID);
				stmt.setInt(10, merchant_ID);
								
				stmt.registerOutParameter(2, java.sql.Types.INTEGER);	
				stmt.execute();
				generatedKey = stmt.getInt(2);
				stmt.close();
				
			} catch (SQLException sqle) {
				AppUtil.console("Deal insert error: "+sqle);
				return -1;
			}
			
			AppUtil.console("Deal_ID: "+generatedKey);
			return generatedKey;
		}


//STILL NEED TO ADD RETRIEVE, UPDATE, DELETE, and ADDITIONAL QUERY INFO
	
// getters 

public Integer getDID() {
	return dID.get();
}


public String getDExpDate() {
	return dExpDate.get();
}

public String getDDescription() {
	return dDescription.get();
}

public Integer getDQuantity() {
	return dQuantity.get();
}

public Double getDOrigPrice() {
	return dOrigPrice.get();
}

public Double getDDealPrice() {
	return dDealPrice.get();
}

public String getDSaleStart() {
	return dSaleStart.get();
}

public String getDSaleEnd() {
	return dSaleEnd.get();
}


public Integer getLID() {
	return lID.get();
}

public Integer getCatID() {
	return catID.get();
}

public Integer getMID() {
	return mID.get();
}

private static boolean connect() {
	if(Deal.conn==null) {
		Deal.conn=new DealConnection(DealConnection.user,DealConnection.pass).getConnection();
		return true;
	}
	return true;
}
	
	
	
	
}