package edu.gmu.cs.infs614.webdealer.model;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;

//import java.sql.PreparedStatement;
//import java.sql.ResultSet;
import java.sql.SQLException;
//import java.util.ArrayList;
//import java.util.Calendar;
//import java.sql.Date;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.ArrayList;




import javafx.beans.property.SimpleDoubleProperty;
import javafx.beans.property.SimpleIntegerProperty;
import javafx.beans.property.SimpleStringProperty;
import javafx.scene.control.TextField;
import edu.gmu.cs.infs614.webdealer.AppUtil;

import edu.gmu.cs.infs614.webdealer.model.connector.DealConnection;
//import edu.gmu.cs.infs614.webdealer.model.connector.OracleConnection;
import edu.gmu.cs.infs614.webdealer.view.FormValidation;


//import edu.gmu.cs.infs614.webdealer.view.FormValidation;





//Immutable tuple (aka primary key)

/*deal_ID INTEGER,
expiration_date DATE,
description VARCHAR2(500),
quantity_limit INTEGER,
original_price REAL,
deal_price REAL,
sale_start_time DATE,
sale_end_time DATE,
location_ID INTEGER,
category_ID INTEGER,
merchant_ID INTEGER
*/

public class Deal {
	
	java.sql.Date sqlDate;
	DateFormat dateFormat = new SimpleDateFormat("dd-MMM-YYYY");
	
	public boolean isInDatabase = false;
	private SimpleIntegerProperty dID; 
	private SimpleStringProperty dExpDate;
	private SimpleStringProperty dDescription;
	private SimpleIntegerProperty dQuantity;
	private SimpleDoubleProperty dOrigPrice;
	private SimpleDoubleProperty dDealPrice;
	private SimpleStringProperty dSaleStart;
	private SimpleStringProperty dSaleEnd;
	private SimpleIntegerProperty lID;
	private SimpleIntegerProperty catID;
	private SimpleIntegerProperty mID;
	private static Connection conn;

	public Deal(Connection conn, Integer deal_ID, String expiration_date, String description, Integer quantity_limit,Double original_price, 
			Double deal_price, String sale_start_time, String sale_end_time, Integer location_ID, Integer category_ID, Integer merchant_ID){
		this.dID=null;
		this.dExpDate=null;
		this.dDescription=null;
		this.dQuantity=null;
		this.dOrigPrice=null;
		this.dDealPrice=null;
		this.dSaleStart=null;
		this.dSaleEnd=null;
		this.lID=null;
		this.catID=null;
		this.mID=null;
		Deal.conn=conn;
		
		// create a new deal in the database
		if(deal_ID == null) {
			int result = create(expiration_date,description,quantity_limit,original_price,deal_price,sale_start_time,sale_end_time,location_ID,category_ID,merchant_ID);
			if(result == -1) {
				isInDatabase = false;
				return;
			}
			else {
				isInDatabase = true;
			}
			
			this.dID = new SimpleIntegerProperty(result);
					
			}
		// create just a deal view
				else {
					this.dID = new SimpleIntegerProperty(deal_ID);
				}
				
				
				this.dExpDate=new SimpleStringProperty(expiration_date);
				this.dDescription=new SimpleStringProperty(description);
				this.dQuantity=new SimpleIntegerProperty(quantity_limit);
				this.dOrigPrice=new SimpleDoubleProperty(original_price);
				this.dDealPrice=new SimpleDoubleProperty(deal_price);
				this.dSaleStart=new SimpleStringProperty(sale_start_time);
				this.dSaleEnd=new SimpleStringProperty(sale_end_time);
				this.lID=new SimpleIntegerProperty(location_ID);
				this.catID=new SimpleIntegerProperty(category_ID);
				this.mID=new SimpleIntegerProperty(merchant_ID);
				AppUtil.console("Deal constructed");
				
				
				
			}
	// Think about how we can model the key that's generated by Oracle	
		public Deal(
				Connection conn,
				TextField tfDeal_ID,
				TextField tfexpiration_date,
				TextField tfdescription,
				TextField tfquantity_limit,
				TextField tforiginal_price,
				TextField tfdeal_price,
				TextField tfsale_start_time,
				TextField tfsale_end_time,
				TextField tflocation_ID,
				TextField tfcategory_ID,
				TextField tfmerchant_ID) {
			Deal.conn = conn;
			// had to check for null before calling tfDealID.getText(), so we just copied the constructor code
			this.dID=null;
			this.dExpDate=null;
			this.dDescription=null;
			this.dQuantity=null;
			this.dOrigPrice=null;
			this.dDealPrice=null;
			this.dSaleStart=null;
			this.dSaleEnd=null;
			this.lID=null;
			this.catID=null;
			this.mID=null;
			
			
			if(tfDeal_ID == null) {
				int result = create(tfexpiration_date.getText(),tfdescription.getText(),Integer.parseInt(tfquantity_limit.getText()),Double.parseDouble(tforiginal_price.getText()),Double.parseDouble(tfdeal_price.getText()),
						tfsale_start_time.getText(),tfsale_end_time.getText(),Integer.parseInt(tflocation_ID.getText()),Integer.parseInt(tfcategory_ID.getText()),Integer.parseInt(tfmerchant_ID.getText()));
				if(result == -1) {
					isInDatabase = false;
					return;
				}
				else {
					isInDatabase = true;
				}
				this.dID = new SimpleIntegerProperty(result);
				}
			else {
				this.dID = new SimpleIntegerProperty(Integer.parseInt(tfDeal_ID.getText()));
			}
			
			
			this.dExpDate=new SimpleStringProperty(tfexpiration_date.getText());
			this.dDescription=new SimpleStringProperty(tfdescription.getText());
			this.dQuantity=new SimpleIntegerProperty(Integer.parseInt(tfquantity_limit.getText()));
			this.dOrigPrice=new SimpleDoubleProperty(Double.parseDouble(tforiginal_price.getText()));
			this.dDealPrice=new SimpleDoubleProperty(Double.parseDouble(tfdeal_price.getText()));
			this.dSaleStart=new SimpleStringProperty(tfsale_start_time.getText());
			this.dSaleEnd=new SimpleStringProperty(tfsale_end_time.getText());
			this.lID=new SimpleIntegerProperty(Integer.parseInt(tflocation_ID.getText()));
			this.catID=new SimpleIntegerProperty(Integer.parseInt(tfcategory_ID.getText()));
			this.mID=new SimpleIntegerProperty(Integer.parseInt(tfmerchant_ID.getText()));

			AppUtil.console("Deal constructed");
		}	

		// CRUD
		private int create(String expiration_date, String description, Integer quantity_limit,Double original_price, 
				Double deal_price, String sale_start_time, String sale_end_time, Integer location_ID, Integer category_ID, Integer merchant_ID) {
			
			if(!connect()) AppUtil.console("Not able to connect to database!");
			
			String sql = "BEGIN INSERT INTO " +
							"Deal (deal_ID,expiration_date,description,quantity_limit,original_price,deal_price,sale_start_name," +
							"sale_end_time,location_ID,category_ID,merchant_ID) " +
							"VALUES (seq_customer.nextval, ?,?,?,?,?,?,?,?,?,?,?) RETURNING deal_ID INTO ?; END;";
			
			java.sql.CallableStatement stmt = null;
			
			
			int generatedKey = 0;
			
			try {
				stmt = conn.prepareCall(sql);
				stmt.setString(1, expiration_date);
				stmt.setString(2, description);
				stmt.setInt(3, quantity_limit);
				stmt.setDouble(4, original_price);
				stmt.setDouble(5, deal_price);
				stmt.setString(6, sale_start_time);
				stmt.setString(7, sale_end_time);
				stmt.setInt(8, location_ID);
				stmt.setInt(9, category_ID);
				stmt.setInt(10, merchant_ID);
								
				stmt.registerOutParameter(11, java.sql.Types.INTEGER);	
				stmt.execute();
				generatedKey = stmt.getInt(11);
				stmt.close();
				
			} catch (SQLException sqle) {
				AppUtil.console("Deal insert error: "+sqle);
				return -1;
			}
			
			AppUtil.console("Deal_ID: "+generatedKey);
			return generatedKey;
		}

		public static ArrayList<Deal> retrieve(Connection conn,TextField tfDeal_ID,TextField tfexpiration_date,TextField tfdescription,
				TextField tfquantity_limit,TextField tforiginal_price,TextField tfdeal_price,TextField tfsale_start_time,TextField tfsale_end_time,TextField tflocation_ID,TextField tfcategory_ID,TextField tfmerchant_ID) 
		{
			if(!connect()) AppUtil.console("Not able to connect to database!");
			
			int start = 0;
			String sqlWhere = " WHERE ";
			if(FormValidation.textFieldTypeInteger(tfDeal_ID)) {
				String deal_ID = "deal_ID = "+"\'"+tfDeal_ID.getText()+"\'";
				if(start>0) sqlWhere+=" AND "+ deal_ID;
				sqlWhere += deal_ID;
				start++;
			}
			if(FormValidation.textFieldNotEmpty(tfexpiration_date)) {
				String expiration_date = "expiration_date = "+"\'"+tfexpiration_date.getText()+"\'";
				if(start>0) sqlWhere+=" AND "+expiration_date;
				else sqlWhere += expiration_date;
				start++;
			}
			
			if(FormValidation.textFieldNotEmpty(tfdescription)) {
				String description = "description = "+"\'"+tfdescription.getText()+"\'";
				if(start>0) sqlWhere+=" AND "+description;
				else sqlWhere += description;
				start++;
			}
			
			if(FormValidation.textFieldNotEmpty(tfquantity_limit)) {
				String quantity_limit = "quantity_limit = "+"\'"+tfquantity_limit.getText()+"\'";
				if(start>0) sqlWhere+=" AND "+quantity_limit;
				else sqlWhere += quantity_limit;
				start++;
			}
			
			
			if(FormValidation.textFieldNotEmpty(tforiginal_price)) {
				String original_price = "original_price = "+"\'"+tforiginal_price.getText()+"\'";
				if(start>0) sqlWhere+=" AND "+original_price;
				else sqlWhere += original_price;
				start++;
			}
			
			if(FormValidation.textFieldNotEmpty(tfdeal_price)) {
				String deal_price = "deal_price = "+"\'"+tfdeal_price.getText()+"\'";
				if(start>0) sqlWhere+=" AND "+deal_price;
				else sqlWhere += deal_price;
				start++;
			}
			
			
			if(FormValidation.textFieldNotEmpty(tfsale_start_time)) {
				String sale_start_time = "sale_start_time = "+"\'"+tfsale_start_time.getText()+"\'";
				if(start>0) sqlWhere+=" AND "+sale_start_time;
				else sqlWhere += sale_start_time;
				start++;
			}
			
			if(FormValidation.textFieldNotEmpty(tfsale_end_time)) {
				String sale_end_time = "sale_end_time = "+"\'"+tfsale_end_time.getText()+"\'";
				if(start>0) sqlWhere+=" AND "+sale_end_time;
				else sqlWhere += sale_end_time;
				start++;
			}
			
			if(FormValidation.textFieldNotEmpty(tflocation_ID)) {
				String location_ID = "location_ID = "+"\'"+tflocation_ID.getText()+"\'";
				if(start>0) sqlWhere+=" AND "+location_ID;
				else sqlWhere += location_ID;
				start++;
			}
			
			if(FormValidation.textFieldNotEmpty(tfcategory_ID)) {
				String category_ID = "category_ID = "+"\'"+tfcategory_ID.getText()+"\'";
				if(start>0) sqlWhere+=" AND "+category_ID;
				else sqlWhere += category_ID;
				start++;
			}
			
			if(FormValidation.textFieldNotEmpty(tfmerchant_ID)) {
				String merchant_ID = "merchant_ID = "+"\'"+tfmerchant_ID.getText()+"\'";
				if(start>0) sqlWhere+=" AND "+merchant_ID;
				else sqlWhere += merchant_ID;
				start++;
			}
				
			PreparedStatement preparedStatement = null;
			
			String selectSQL;
			if(start>0) {
				selectSQL = "SELECT * FROM DEAL "+sqlWhere;
			}else {
				selectSQL = "SELECT * FROM DEAL";
			}
			
			AppUtil.console("Select String: "+selectSQL);
	 
			ResultSet rs = null;
			ArrayList<Deal> dl = new ArrayList<Deal>();
			
			
			try {

				preparedStatement = conn.prepareStatement(selectSQL);
				
	 
				// execute select SQL
				rs = preparedStatement.executeQuery();
	 
				while (rs.next()) {
					
					dl.add(new Deal(Deal.conn,
							rs.getInt("deal_ID"),
							rs.getString("expiration_date"),
							rs.getString("description"),
							rs.getInt("quantity_limit"),
							rs.getDouble("original_price"),
							rs.getDouble("deal_price"),
							rs.getString("sale_start_time"),
							rs.getString("sale_end_time"),
							rs.getInt("location_ID"),
							rs.getInt("category_ID"),
							rs.getInt("merchant_ID")));

					AppUtil.console("deal_ID : " + rs.getString("deal_ID"));
					AppUtil.console("expiration_date : " + rs.getString("expiration_date"));
					AppUtil.console("description : " + rs.getString("description"));
					AppUtil.console("quantity_limit : " + rs.getInt("quantity_limit"));
					AppUtil.console("original_price : " + rs.getDouble("original_price"));
					AppUtil.console("deal_price : " + rs.getDouble("deal_price"));
					AppUtil.console("sale_start_time : " + rs.getString("sale_start_time"));
					AppUtil.console("sale_end_time : " + rs.getString("sale_end_time"));
					AppUtil.console("location_ID : " + rs.getInt("location_ID"));
					AppUtil.console("category_ID : " + rs.getInt("category_ID"));
					AppUtil.console("merchant_ID : " + rs.getInt("merchant_ID"));
	 
				}
	 
				preparedStatement.close();
				//rs.first(); // It seems this non-scrollable result set resets to first automagically
				
				
			} catch (SQLException e) {
	 
				AppUtil.console(e.getMessage());
				
			}
			
			
			return dl;
	 
		}
			
		public static boolean update(Deal oldDeal, Deal newDeal) {
			if(!connect()) AppUtil.console("Not able to connect to database!");
			
			
			AppUtil.console("Modifying deal: "+oldDeal.getDID());
			
			String sql = "UPDATE Deal SET "+
					"expiration_date = \'"+newDeal.getDExpDate()+"\',"+
					"description = \'"+newDeal.getDDescription()+"\',"+
					"quantity_limit = \'"+newDeal.getDQuantity()+"\',"+
					"original_price = \'"+newDeal.getDOrigPrice()+"\',"+
					"deal_price = \'"+newDeal.getDDealPrice()+"\',"+
					"sale_start_time = \'"+newDeal.getDSaleStart()+"\',"+
					"sale_end_time = \'"+newDeal.getDSaleEnd()+"\',"+
					"location_ID = \'"+newDeal.getLID()+"\',"+
					"category_ID = \'"+newDeal.getCatID()+"\',"+
					"merchant_ID = \'"+newDeal.getMID()+"\'"+
					
					" WHERE deal_ID = \'"+newDeal.getDID()+"\'";
			
		
			AppUtil.console("UPDATE: "+sql);

			PreparedStatement preparedStatement = null;
			try {
				preparedStatement = conn.prepareStatement(sql);
				preparedStatement.executeQuery();
				preparedStatement.close();
			} catch (Exception e) {
				
				AppUtil.console("M: Most likely a DDL error, not a problem."+e);
				return false;
				
			}
			return true;
		}		
			
		public static boolean delete(Deal oldDeal) {
			if(!connect()) AppUtil.console("Not able to connect to database!");
			
			
			AppUtil.console("Deleting deal: "+oldDeal.getDID());
			
			String sql = "DELETE FROM Deal "+ 
					"WHERE deal_ID = \'"+oldDeal.getDID()+"\'";
			
			AppUtil.console("DELETE: "+sql);

			PreparedStatement preparedStatement = null;
			try {
				preparedStatement = conn.prepareStatement(sql);
				preparedStatement.executeQuery();
				preparedStatement.close();
			} catch (Exception e) {
				AppUtil.console("M: Most likely a DDL error, not a problem."+e);
			}
			return true;
		}

	
// getters 

public Integer getDID() {
	return dID.get();
}


public String getDExpDate() {
	return dExpDate.get();
}

public String getDDescription() {
	return dDescription.get();
}

public Integer getDQuantity() {
	return dQuantity.get();
}

public Double getDOrigPrice() {
	return dOrigPrice.get();
}

public Double getDDealPrice() {
	return dDealPrice.get();
}

public String getDSaleStart() {
	return dSaleStart.get();
}

public String getDSaleEnd() {
	return dSaleEnd.get();
}


public Integer getLID() {
	return lID.get();
}

public Integer getCatID() {
	return catID.get();
}

public Integer getMID() {
	return mID.get();
}

private static boolean connect() {
	if(Deal.conn==null) {
		Deal.conn=new DealConnection(DealConnection.user,DealConnection.pass).getConnection();
		return true;
	}
	return true;
}
	
	
	
	
}